on:
  issues:
    types: [opened]
    
name: Jira Issue Create

jobs:
  jira-issue-create:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
          project: ${{ secrets.JIRA_PROJECT_SDK }}
          issuetype: Task
          summary: ${{github.event.issue.title}}

    - name: Log created Jira issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
      
    - name: Create comment with Jira issue number and link
      id: comment
      uses: peter-evans/create-or-update-comment@v3
      with:
          issue-number: ${{github.event.issue.number}}
          body: ${{ steps.create.outputs.issue }} ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create.outputs.issue }}
      
